export const SET_MY_COMMUNITY = "SET_MY_COMMUNITY";
export const ADD_TO_MY_COMMUNITY = "ADD_TO_MY_COMMUNITY";
export const REMOVE_TO_MY_COMMUNITY = "REMOVE_TO_MY_COMMUNITY";

export const SET_AVAILABLE_COMMUNITY = "SET_AVAILABLE_COMMUNITY";
export const ADD_COMMUNITY = "ADD_COMMUNITY";
export const REMOVE_COMMUNITY = "REMOVE_COMMUNITY";

export const DELETE_COMMUNITY = "DELETE_COMMUNITY";
export const UPDATE_COMMUNITY = "UPDATE_COMMUNITY";

export const SET_MESSAGES = "SET_MESSAGES";
export const ADD_MESSAGE = "ADD_MESSAGE";

export const SET_FEED = "SET_FEED";
export const ADD_FEED = "ADD_FEED";
export const UPDATE_FEED = "UPDATE_FEED";
export const REMOVE_FEED = "REMOVE_FEED";

export const SET_CURRENT_USER = "GET_CURRENT_USER";
export const CURRENT_USER_ADD_COMM = "CURRENT_USER_ADD_COMM";
export const CURRENT_USER_REMOVE_COMM = "CURRENT_USER_REMOVE_COMM";
